/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package chooseuradventure;

import java.util.ArrayList;
import java.util.Map;
import javax.swing.JOptionPane;

/**
 *
 * @author Greg
 */
public class MainGUI extends javax.swing.JFrame {

    /**
     * Creates new form MainGUI
     */
    private TehAdventure adventure;
    private ArrayList<Map<Object, String>> intermediate=new ArrayList<>();
    
    public MainGUI() {
        initComponents();
        this.adventure=new TehAdventure();
        this.jTextArea1.append(adventure.getMainText());
        this.jButton1.setText(adventure.getButtonOne());
        this.jButton2.setText(adventure.getButtonTwo());
        this.jButton3.setText(adventure.getButtonThree());
    }
    
    public MainGUI(ArrayList<Map<Object, String>> intermediate) {
        initComponents();
        
        this.intermediate = intermediate;
        this.adventure=new TehAdventure(intermediate);
        this.jTextArea1.append(adventure.getMainText());
        this.jButton1.setText(adventure.getButtonOne());
        this.jButton2.setText(adventure.getButtonTwo());
        this.jButton3.setText(adventure.getButtonThree());
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("jButton2");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("jButton3");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        if(intermediate.size()<=Integer.parseInt(adventure.getSingleValue(0))){
            //JOptionPane.showInputDialog("Scene Does not exist");
            JOptionPane.showConfirmDialog(rootPane, "Scene Does not exist");
            
        } else {
        
        adventure.enterAndUpdate(Integer.parseInt(adventure.getSingleValue(0)));
        this.jTextArea1.setText(null);
        this.jTextArea1.append(adventure.getMainText());
        this.jButton1.setText(adventure.getButtonOne());
        this.jButton2.setText(adventure.getButtonTwo());
        this.jButton3.setText(adventure.getButtonThree());
        System.out.println(this.adventure.getSingleValue(0) + " " + this.adventure.getSingleValue(1) + " " + this.adventure.getSingleValue(2));
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        if(intermediate.size()<=Integer.parseInt(adventure.getSingleValue(1))){
            //JOptionPane.showInputDialog("Scene Does not exist");
            JOptionPane.showConfirmDialog(rootPane, "Scene Does not exist");
        } else {
        
        adventure.enterAndUpdate(Integer.parseInt(adventure.getSingleValue(1)));
        this.jTextArea1.setText(null);
        this.jTextArea1.append(adventure.getMainText());
        this.jButton1.setText(adventure.getButtonOne());
        this.jButton2.setText(adventure.getButtonTwo());
        this.jButton3.setText(adventure.getButtonThree());
        System.out.println(this.adventure.getSingleValue(0) + " " + this.adventure.getSingleValue(1) + " " + this.adventure.getSingleValue(2));
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        
        if(intermediate.size()<=Integer.parseInt(adventure.getSingleValue(2))){
            //JOptionPane.showInputDialog("Scene Does not exist");
            JOptionPane.showConfirmDialog(rootPane, "Scene Does not exist");
        } else {
        
        
        adventure.enterAndUpdate(Integer.parseInt(adventure.getSingleValue(2)));
        this.jTextArea1.setText(null);
        this.jTextArea1.append(adventure.getMainText());
        this.jButton1.setText(adventure.getButtonOne());
        this.jButton2.setText(adventure.getButtonTwo());
        this.jButton3.setText(adventure.getButtonThree());
        System.out.println(this.adventure.getSingleValue(0) + " " + this.adventure.getSingleValue(1) + " " + this.adventure.getSingleValue(2));
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
